name: Build FloatClock
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: compile
        run: make all

      - name: Manually construct .app bundle
        run: |
          # 手动创建macOS App包目录结构
          mkdir -p FloatClock.app/Contents/MacOS
          mkdir -p FloatClock.app/Contents/Resources
          # 复制编译出来的二进制
          cp FloatClock FloatClock.app/Contents/MacOS/FloatClock
          # 拷贝plist配置文件
          cp FloatClock.plist.in FloatClock.app/Contents/Info.plist

      - name: Zip app bundle
        run: zip -r FloatClock.zip FloatClock.app

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: FloatClock-zip
          path: FloatClock.zip
          if-no-files-found: error
